services:
  db:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d app_db -h localhost -p 5432",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: